[tool.poetry]
name = "web-app"
version = "0.1.0"
description = ""
authors = ["Xavier"]
readme = "README.md"


[tool.poetry.dependencies]
python = "^3.10"
flask = "^2.3.2"
tex2lambda = "^0.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
